'------------------------------------------------------------------------------
'  <auto-generated>
'      This code was generated by coded UI test builder.
'      Version: 12.0.0.0
'
'      Changes to this file may cause incorrect behavior and will be lost if
'      the code is regenerated.
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UITesting.WinControls
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace CodedUITestProject1
    
    <GeneratedCode("Coded UITest Builder", "12.0.21005.1")>  _
    Partial Public Class UIMap
        
        '''<summary>
        '''AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        '''</summary>
        Public Sub AssertMethod1()
            Dim uIValueClient As WinClient = Me.UISpreadsheetPanel1Window.UIItemWindow.UIValueClient

            'Verify that the 'ControlType' property of 'Value' client equals 'Client'
            Assert.AreEqual(Me.AssertMethod1ExpectedValues.UIValueClientControlType, uIValueClient.ControlType.ToString)
        End Sub
        
        '''<summary>
        '''RecordedMethod1
        '''</summary>
        Public Sub RecordedMethod1()
            Dim uIDesktopList As WinList = Me.UIProgramManagerWindow.UIFolderViewWindow.UIDesktopList
            Dim uIValueClient As WinClient = Me.UISpreadsheetPanel1Window.UIItemWindow.UIValueClient

            'Click 'Desktop' list box
            Mouse.Click(uIDesktopList, New Point(905, 199))

            'Move 'Value' client
            Mouse.StartDragging(uIValueClient, New Point(1040, 522))
            Mouse.StopDragging(uIValueClient, -412, -275)
        End Sub
        
        #Region "Properties"
        Public Overridable ReadOnly Property AssertMethod1ExpectedValues() As AssertMethod1ExpectedValues
            Get
                If (Me.mAssertMethod1ExpectedValues Is Nothing) Then
                    Me.mAssertMethod1ExpectedValues = New AssertMethod1ExpectedValues()
                End If
                Return Me.mAssertMethod1ExpectedValues
            End Get
        End Property
        
        Public ReadOnly Property UISpreadsheetPanel1Window() As UISpreadsheetPanel1Window
            Get
                If (Me.mUISpreadsheetPanel1Window Is Nothing) Then
                    Me.mUISpreadsheetPanel1Window = New UISpreadsheetPanel1Window()
                End If
                Return Me.mUISpreadsheetPanel1Window
            End Get
        End Property
        
        Public ReadOnly Property UIProgramManagerWindow() As UIProgramManagerWindow
            Get
                If (Me.mUIProgramManagerWindow Is Nothing) Then
                    Me.mUIProgramManagerWindow = New UIProgramManagerWindow()
                End If
                Return Me.mUIProgramManagerWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mAssertMethod1ExpectedValues As AssertMethod1ExpectedValues
        
        Private mUISpreadsheetPanel1Window As UISpreadsheetPanel1Window
        
        Private mUIProgramManagerWindow As UIProgramManagerWindow
        #End Region
    End Class
    
    '''<summary>
    '''Parameters to be passed into 'AssertMethod1'
    '''</summary>
    <GeneratedCode("Coded UITest Builder", "12.0.21005.1")>  _
    Public Class AssertMethod1ExpectedValues
        
        #Region "Fields"
        '''<summary>
        '''Verify that the 'ControlType' property of 'Value' client equals 'Client'
        '''</summary>
        Public UIValueClientControlType As String = "Client"
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.21005.1")>  _
    Public Class UISpreadsheetPanel1Window
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.AccessibleName) = "Value"
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIItemWindow() As UIItemWindow
            Get
                If (Me.mUIItemWindow Is Nothing) Then
                    Me.mUIItemWindow = New UIItemWindow(Me)
                End If
                Return Me.mUIItemWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIItemWindow As UIItemWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.21005.1")>  _
    Public Class UIItemWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties.Add(New PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains))
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIValueClient() As WinClient
            Get
                If (Me.mUIValueClient Is Nothing) Then
                    Me.mUIValueClient = New WinClient(Me)
                End If
                Return Me.mUIValueClient
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIValueClient As WinClient
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.21005.1")>  _
    Public Class UIProgramManagerWindow
        Inherits WinWindow
        
        Public Sub New()
            MyBase.New
            Me.SearchProperties(WinWindow.PropertyNames.Name) = "Program Manager"
            Me.SearchProperties(WinWindow.PropertyNames.ClassName) = "Progman"
            Me.WindowTitles.Add("Program Manager")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIFolderViewWindow() As UIFolderViewWindow
            Get
                If (Me.mUIFolderViewWindow Is Nothing) Then
                    Me.mUIFolderViewWindow = New UIFolderViewWindow(Me)
                End If
                Return Me.mUIFolderViewWindow
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIFolderViewWindow As UIFolderViewWindow
        #End Region
    End Class
    
    <GeneratedCode("Coded UITest Builder", "12.0.21005.1")>  _
    Public Class UIFolderViewWindow
        Inherits WinWindow
        
        Public Sub New(ByVal searchLimitContainer As UITestControl)
            MyBase.New(searchLimitContainer)
            Me.SearchProperties(WinWindow.PropertyNames.ControlId) = "1"
            Me.WindowTitles.Add("Program Manager")
        End Sub
        
        #Region "Properties"
        Public ReadOnly Property UIDesktopList() As WinList
            Get
                If (Me.mUIDesktopList Is Nothing) Then
                    Me.mUIDesktopList = New WinList(Me)
                    Me.mUIDesktopList.SearchProperties(WinList.PropertyNames.Name) = "Desktop"
                    Me.mUIDesktopList.WindowTitles.Add("Program Manager")
                End If
                Return Me.mUIDesktopList
            End Get
        End Property
        #End Region
        
        #Region "Fields"
        Private mUIDesktopList As WinList
        #End Region
    End Class
End Namespace
